(use-package projectile
  :config
  (projectile-mode +1))

(defun my-cmake-build ()
  "Build the cmake project in the current directory."
  (interactive)
  (let ((project-root (projectile-project-root)))
    (if (not project-root)
        (error "Could not find project root directory")
      (let* ((build-dir (concat project-root "build"))
             (command (concat "cd " build-dir " && cmake .. && make"))
             (compilation-buffer-name-function (lambda (major-mode-name) "*cmake-build*")))
        (unless (file-directory-p build-dir)
          (make-directory build-dir))
        (setq default-directory build-dir)
        (compile command)))))

(defun compile-project (target)
  (interactive "MEnter target name: ")
  (cmake-ide-run-cmake)
  (let ((build-dir (concat (projectile-project-root) "build/"))
        (compile-command (concat "cd " (projectile-project-root) " && cmake --build build --target " target)))
    (compile compile-command)))

(defun build-and-run-project (target)
  (interactive "MEnter target name: ")
  (compile-project target)
  (let ((build-dir (concat (projectile-project-root) "build/"))
        (compile-command (concat "cd " (projectile-project-root) " && cmake --build build --target " target " && " (projectile-project-root) "build/" target)))
    (compile compile-command)
    (async-shell-command (concat (projectile-project-root) "build/" target))))

(defun build-and-debug-project (target)
  (interactive "MEnter target name: ")
  (compile-project target)
  (let ((build-dir (concat (projectile-project-root) "build/"))
        (compile-command (concat "cd " (projectile-project-root) " && cmake --build build --target " target)))
    (compile compile-command)
    (gdb (concat "gdb -i=mi " (concat (projectile-project-root) "build/" target)))))

(global-set-key (kbd "<f5>") 'build-and-run-project)
(global-set-key (kbd "<f6>") 'build-and-debug-project)
(global-set-key (kbd "<f7>") 'compile-project)
(global-set-key (kbd "<f9>") 'my-cmake-build)
